### ISSUE TITLE
Switch to Highcharts

### ISSUE THREAD

**Issue by loudnate** [loudnate/openaps-monitor#1]
Google Visualization TOS forbids downloading their libraries. Highcharts could be a reasonable alternative.

http://www.highcharts.com/demo/spline-irregular-time

**Comment by loudnate** [comment]
@channemann take a look at this library and see how the new feature requests might fit. We'll need to migrate away from G-charts.

**Comment by channemann** [comment]
Yeah, there are some nice ones in there—seems pretty responsive, too.

http://www.highcharts.com/demo/synchronized-charts is a good example; could line up glucose, basal rate, IOB, COB.

**Comment by loudnate** [comment]
Started this work in a branch here: https://github.com/loudnate/openaps-monitor/tree/loudnate/highcharts

**Comment by channemann** [comment]
Very cool, let me know if you'd like me to test it or if there's something
I can easily jump in and work on.

On Sun, Oct 11, 2015 at 2:51 PM, Nathan Racklyeft notifications@github.com
wrote:

> Started this work in a branch here:
> https://github.com/loudnate/openaps-monitor/tree/loudnate/highcharts
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/loudnate/openaps-monitor/issues/1#issuecomment-147249359
> .

## 

Chris Hannemann
chris.hannemann@gmail.com

**Comment by loudnate** [comment]
I'll make sure the remote branch always stays "working". Currently, it's displaying both chart types, so it would be good if you wanted to start testing.

**Comment by channemann** [comment]
Got it up and running, looks like a good start.

On Mon, Oct 12, 2015 at 8:52 AM, Nathan Racklyeft notifications@github.com
wrote:

> I'll make sure the remote branch always stays "working". Currently, it's
> displaying both chart types, so it would be good if you wanted to start
> testing.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/loudnate/openaps-monitor/issues/1#issuecomment-147444603
> .

## 

Chris Hannemann
chris.hannemann@gmail.com
