### ISSUE TITLE
Use Points Instead of Line for Historical Data

### ISSUE THREAD

**Issue by channemann** [loudnate/openaps-monitor#16]
Historical data looks odd when there are calibration shifts or periods of missing values with the line graph. Using points (dots) would help show this more clearly.

**Comment by loudnate** [comment]
Rather than using dots, what if we kept the nulls for missing values and pulled fingersticks into their own series?

**Comment by channemann** [comment]
I still tend to have a preference for individual points (engineering hammered that into me), but a line for CGM readings that breaks for null values and split-out fingerstick values works well.

**Comment by loudnate** [comment]
Fixed in #36
